name: DeathBan
main: info.kanlaki101.deathban.DeathBan
version: 0.4
author: Kanlaki101
depend: [Vault]
description: >
             Temporarily ban players on death
commands:
  dbreload:
    description: Reload the configuration file
    usage: /<command>
  dbunban:
    description: Manually unban a player
    usage: /<command> <player>
  dblives:
    aliases: [lives, l]
    description: View/Edit a players lives
    usage: /<command> <player:add:set> [player] [amount]
    
permissions:
    deathban.*:
        description: Gives the user all DeathBan features
        children:
            deathban.exception: true
            deathban.reload: true
            deathban.unban: true
            deathban.editlives: true
    deathban.exception:
        description: Users will not be banned on death
        default: op
    deathban.reload:
        description: Ability to reload the config file
        default: op
    deathban.unban:
        description: Ability to unban a player
        default: op
    deathban.editlives:
        desctiption: Ability to edit/add to a players amount of lives
        default: op