name: DeathBan
main: me.kanlaki101.DeathBan.DeathBan
version: 0.3
author: Kanlaki101
depend: [Vault]
description: >
             Temporarily ban players on death
commands:
  dbreload:
    description: Reload the configuration file
    usage: /<command>
  dbunban:
    description: Manually unban a player
    usage: /<command>
    
permissions:
    deathban.*:
        description: Gives the user all DeathBan features
        children:
            deathban.exception: true
            deathban.reload: true
            deathban.unban: true
    deathban.exception:
        description: Users will not be banned on death
        default: op
    deathban.reload:
        description: Ability to reload the config file
        default: op
    deathban.unban:
        description: Ability to unban a player
        default: op